package avcodec;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.ochafik.lang.jnaerator.runtime.Union;
import com.sun.jna.Pointer;
/**
 * <i>native declaration : src/main/headers/libavcodec/opt.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVOption2 extends Structure<AVOption2, AVOption2.ByValue, AVOption2.ByReference > {
	/// C type : const char*
	public Pointer name;
	/**
	 * short English help text<br>
	 * @todo What about other languages?<br>
	 * C type : const char*
	 */
	public Pointer help;
	/**
	 * The offset relative to the context structure where the option<br>
	 * value is stored. It should be 0 for named constants.
	 */
	public int offset;
	/**
	 * @see AVOptionType<br>
	 * C type : AVOptionType
	 */
	public int type;
	/**
	 * the default value for scalar options<br>
	 * C type : default_val_union
	 */
	public default_val_union default_val;
	/// < minimum valid value for the option
	public double min;
	/// < maximum valid value for the option
	public double max;
	public int flags;
	/**
	 * The logical unit to which the option belongs. Non-constant<br>
	 * options and corresponding named constants share the same<br>
	 * unit. May be NULL.<br>
	 * C type : const char*
	 */
	public Pointer unit;
	/// <i>native declaration : src/main/headers/libavcodec/opt.h:112</i>
	public static class default_val_union extends Union<default_val_union, default_val_union.ByValue, default_val_union.ByReference > {
		public double dbl;
		/// C type : const char*
		public Pointer str;
		public default_val_union() {
			super();
		}
		public default_val_union(double dbl) {
			super();
			this.dbl = dbl;
			setType(java.lang.Double.TYPE);
		}
		/// @param str C type : const char*
		public default_val_union(Pointer str) {
			super();
			this.str = str;
			setType(com.sun.jna.Pointer.class);
		}
		protected ByReference newByReference() { return new ByReference(); }
		protected ByValue newByValue() { return new ByValue(); }
		protected default_val_union newInstance() { return new default_val_union(); }
		public static default_val_union[] newArray(int arrayLength) {
			return Union.newArray(default_val_union.class, arrayLength);
		}
		public static class ByReference extends default_val_union implements Structure.ByReference {
			
		};
		public static class ByValue extends default_val_union implements Structure.ByValue {
			
		};
	};
	public AVOption2() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"name", "help", "offset", "type", "default_val", "min", "max", "flags", "unit"});
	}
	/**
	 * @param name C type : const char*<br>
	 * @param help short English help text<br>
	 * @todo What about other languages?<br>
	 * C type : const char*<br>
	 * @param offset The offset relative to the context structure where the option<br>
	 * value is stored. It should be 0 for named constants.<br>
	 * @param type @see AVOptionType<br>
	 * C type : AVOptionType<br>
	 * @param default_val the default value for scalar options<br>
	 * C type : default_val_union<br>
	 * @param min < minimum valid value for the option<br>
	 * @param max < maximum valid value for the option<br>
	 * @param unit The logical unit to which the option belongs. Non-constant<br>
	 * options and corresponding named constants share the same<br>
	 * unit. May be NULL.<br>
	 * C type : const char*
	 */
	public AVOption2(Pointer name, Pointer help, int offset, int type, default_val_union default_val, double min, double max, int flags, Pointer unit) {
		super();
		this.name = name;
		this.help = help;
		this.offset = offset;
		this.type = type;
		this.default_val = default_val;
		this.min = min;
		this.max = max;
		this.flags = flags;
		this.unit = unit;
		initFieldOrder();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected AVOption2 newInstance() { return new AVOption2(); }
	public static AVOption2[] newArray(int arrayLength) {
		return Structure.newArray(AVOption2.class, arrayLength);
	}
	public static class ByReference extends AVOption2 implements Structure.ByReference {
		
	};
	public static class ByValue extends AVOption2 implements Structure.ByValue {
		
	};
}
