package avcodec;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.ptr.PointerByReference;
/**
 * <i>native declaration : src/main/headers/libavcodec/avcodec.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVSubtitle extends Structure<AVSubtitle, AVSubtitle.ByValue, AVSubtitle.ByReference > {
	/// 0 = graphics
	public short format;
	/// relative to packet pts, in ms
	public int start_display_time;
	/// relative to packet pts, in ms
	public int end_display_time;
	public int num_rects;
	/// C type : AVSubtitleRect**
	public PointerByReference rects;
	/// < Same as packet pts, in AV_TIME_BASE
	public long pts;
	public AVSubtitle() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"format", "start_display_time", "end_display_time", "num_rects", "rects", "pts"});
	}
	/**
	 * @param format 0 = graphics<br>
	 * @param start_display_time relative to packet pts, in ms<br>
	 * @param end_display_time relative to packet pts, in ms<br>
	 * @param rects C type : AVSubtitleRect**<br>
	 * @param pts < Same as packet pts, in AV_TIME_BASE
	 */
	public AVSubtitle(short format, int start_display_time, int end_display_time, int num_rects, PointerByReference rects, long pts) {
		super();
		this.format = format;
		this.start_display_time = start_display_time;
		this.end_display_time = end_display_time;
		this.num_rects = num_rects;
		this.rects = rects;
		this.pts = pts;
		initFieldOrder();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected AVSubtitle newInstance() { return new AVSubtitle(); }
	public static AVSubtitle[] newArray(int arrayLength) {
		return Structure.newArray(AVSubtitle.class, arrayLength);
	}
	public static class ByReference extends AVSubtitle implements Structure.ByReference {
		
	};
	public static class ByValue extends AVSubtitle implements Structure.ByValue {
		
	};
}
