package avutil;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
/**
 * <i>native declaration : src/main/headers/libavutil/log.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVClass extends Structure<AVClass, AVClass.ByValue, AVClass.ByReference > {
	/**
	 * The name of the class; usually it is the same name as the<br>
	 * context structure type to which the AVClass is associated.<br>
	 * C type : const char*
	 */
	public Pointer class_name;
	/**
	 * A pointer to a function which returns the name of a context<br>
	 * instance ctx associated with the class.<br>
	 * C type : item_name_callback
	 */
	public AVClass.item_name_callback item_name;
	/**
	 * a pointer to the first option specified in the class if any or NULL<br>
	 * * @see av_set_default_options()<br>
	 * C type : AVOption*
	 */
	public avcodec.AVOption.ByReference option;
	public int version;
	/// <i>native declaration : src/main/headers/libavutil/log.h</i>
	public interface item_name_callback extends Callback {
		String apply(Pointer ctx);
	};
	public AVClass() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"class_name", "item_name", "option", "version"});
	}
	/**
	 * @param class_name The name of the class; usually it is the same name as the<br>
	 * context structure type to which the AVClass is associated.<br>
	 * C type : const char*<br>
	 * @param item_name A pointer to a function which returns the name of a context<br>
	 * instance ctx associated with the class.<br>
	 * C type : item_name_callback<br>
	 * @param option a pointer to the first option specified in the class if any or NULL<br>
	 * * @see av_set_default_options()<br>
	 * C type : AVOption*
	 */
	public AVClass(Pointer class_name, AVClass.item_name_callback item_name, avcodec.AVOption.ByReference option, int version) {
		super();
		this.class_name = class_name;
		this.item_name = item_name;
		this.option = option;
		this.version = version;
		initFieldOrder();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected AVClass newInstance() { return new AVClass(); }
	public static AVClass[] newArray(int arrayLength) {
		return Structure.newArray(AVClass.class, arrayLength);
	}
	public static class ByReference extends AVClass implements Structure.ByReference {
		
	};
	public static class ByValue extends AVClass implements Structure.ByValue {
		
	};
}
